apiVersion: v1
kind: Secret
metadata:
  name: kong-gateway-secrets
  namespace: development
type: Opaque
stringData:
  KONG_DATABASE: postgres
  KONG_PG_HOST: kong_db
  KONG_PG_USER: kong
  KONG_PG_PASSWORD: kongpass
  KONG_PROXY_ACCESS_LOG: /dev/stdout
  KONG_ADMIN_ACCESS_LOG: /dev/stdout
  KONG_PROXY_ERROR_LOG: /dev/stderr
  KONG_ADMIN_ERROR_LOG: /dev/stderr
  KONG_ADMIN_LISTEN:  0.0.0.0:8001
  KONG_ADMIN_GUI_URL: http://localhost:8002
  KONG_PLUGINS: bundled,scope-acl