kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: dp-icea-brutm-cluster
nodes:
  - role: control-plane
    image: kindest/node:v1.27.3
    kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "ingress-ready=true"   
          max-pods: "100"
  - role: worker
    image: kindest/node:v1.27.3
  - role: worker
    image: kindest/node:v1.27.3